### ISSUE TITLE
We are sending keys globally

### ISSUE THREAD

**Issue by margani** [Aqovia/ServiceBusMessageForwarder#3]
[here](https://github.com/Aqovia/ServiceBusMessageForwarder/blob/68b59d44e0acec3654bb49e7c92dfe7aa6d78834/ServiceBusMessageForwarder/ServiceBusMessageForwarder.cs#L229), we are sending keys even when the application is not active.

You could use the solution [here](https://stackoverflow.com/a/20628511/87514).

**Comment by rickyattiliaaq** [comment]
@margani This has been fixed in commit 127f3c7
